/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paperserver.h"

bool_t
xdr_add_article_in (XDR *xdrs, add_article_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->content.content_val, (u_int *) &objp->content.content_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_articles (XDR *xdrs, articles *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->content.content_val, (u_int *) &objp->content.content_len, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (articles), (xdrproc_t) xdr_articles))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_article_out (XDR *xdrs, list_article_out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (list_article_out), (xdrproc_t) xdr_list_article_out))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_article_info_out (XDR *xdrs, article_info_out *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fetch_article_out (XDR *xdrs, fetch_article_out *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->content.content_val, (u_int *) &objp->content.content_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_article_num (XDR *xdrs, article_num *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_info_res (XDR *xdrs, info_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_article_info_out (xdrs, &objp->info_res_u.info))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_list_res (XDR *xdrs, list_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_list_article_out (xdrs, &objp->list_res_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
